apiVersion: v1
kind: ServiceAccount
metadata:
  name: infres-serviceaccount
  namespace: infres
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infres-rbac
  namespace: infres
subjects:
- kind: ServiceAccount
  name: infres-serviceaccount
  namespace: infres
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
